### ISSUE TITLE
Small guide how to build the TWRP recovery

### ISSUE THREAD

**Issue by bovirus** [Grace5921/TwrpBuilder#13]
@berkantkz 
@amitkhairnar44 

Hi.

I have the original stock recovery file (recovery.,img).
I can use Windows/CygWin/Linux (Ubuntu)

How can build the TWRP recovery using one of these operating system/emulation?
What are the requirements.
Where can I find a simple detailed guide hot to do it?

Thanks.

**Comment by surendrajat** [comment]
There's a wiki [here](https://github.com/TwrpBuilder/twrpbuilder_tree_generator/wiki).
