### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by carlitros900** [Grace5921/TwrpBuilder#14]
I am unable to make a request. Recovery image is generated but there is an upload error.
Android Version: 6.0
Kernel: 3.18.22
Device rooted with magisk.
Best Regards.

**Comment by berkantkz** [comment]
@carlitros900 Does it says something else than "error"?

**Comment by carlitros900** [comment]
It seems init upload, but inmediately fails with message: Failed to upload data.
