### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [Grace5921/TwrpBuilder#21]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by Dyneteve** [comment]
Ok make a logo

**Comment by mansya** [comment]
I have design logo for this project. what do you think ? do you like it ? which one do you like ? If there is a change. please let me know 
![twrpbuilder](https://user-images.githubusercontent.com/33461607/44866788-5714c280-acb0-11e8-9201-8644ad40edd8.png)

I use the tool icon because TWRP is a basic setting on Android systems. and the reason I use the android icon by using a safety helmet is because in this project there is the word "builder" so I use it to explain how this project works.

**Comment by berkantkz** [comment]
Thanks. We will think about them.

**Comment by mansya** [comment]
I will wait happily

**Comment by surendrajat** [comment]
@mansya We genuinely appreciate your efforts and the proposal. I, as a suggestion, want to put a point or two about this project, in order for you to update it.
The whole point of this project is to provide users `TWRP recovery`, so it'd be nice if the design reflects `TWRP` logo (the two arrows facing each other) somehow.
Also, It's not necessary to show android logo (because twrp means android ;)) but it's up to you.
About color 2nd & 8th ones look good to me but I may have an eye condition so use your best call.

**Comment by mansya** [comment]
ok sir. I will use the two arrows facing each other logo. I will condition the layout. which obviously I will improve as best as possible. thank you for the advice sir. this is very helpful.

**Comment by mansya** [comment]
hi sir. how about this ? do you like it? if yes. which one do you like ?
![twrpbuilder](https://user-images.githubusercontent.com/33461607/44890945-f95f9500-ad06-11e8-843e-73d7b8b22a73.png)

**Comment by surendrajat** [comment]
Well, these look cool. Let's see what @berkantkz and other think of it...
Could you make the arrows a bit wider in meantime?

**Comment by berkantkz** [comment]
I agree with @Surendrajat. It'd look better if the arrows were wider.

**Comment by mansya** [comment]
I've made changes in the arrow. can it be like this ?
![twrpbuilder](https://user-images.githubusercontent.com/33461607/44905399-2da17880-ad3c-11e8-9cf8-cd829a149737.png)

**Comment by mansya** [comment]
hi @Surendrajat and @berkantkz. which one will you choose?

**Comment by Dyneteve** [comment]
Make arrow wider even more

**Comment by berkantkz** [comment]
Also, make the arrows white on the 4th one, please.

Edit: I hadn't meant to mention @Dyneteve ;/

**Comment by Dyneteve** [comment]
Like the arrow is ok but its like stretched

**Comment by yshalsager** [comment]
so, the 4th is the best. Can you try making Arrows white? :+1: 

berkantkz edited: #4 refers to issue 4 here. Sorry for disturbing but I do care about these kind of things :3

**Comment by mansya** [comment]
did you mean like this sir ?
![4](https://user-images.githubusercontent.com/33461607/44941733-853bf480-adcd-11e8-8331-689b6a5005ed.png)

**Comment by yshalsager** [comment]
Yeah. Seems perfect!

**Comment by mansya** [comment]
is it possible to make pull requests?

**Comment by berkantkz** [comment]
That's good. Please create a pull request in which you replace logo with this new one.

**Comment by mansya** [comment]
ok. i'll make it now.

**Comment by Dyneteve** [comment]
I guess closed

**Comment by mansya** [comment]
Hi sir. I have uploaded all files to this [**drive**](https://drive.google.com/open?id=1NF-6-cTQHl0rzk8jV7qxbLpQAsLRmEJi). and I have sent you a pull request. please check
