### ISSUE TITLE
App shows that I don't have root

### ISSUE THREAD

**Issue by mohammadshaba** [Grace5921/TwrpBuilder#23]
Hello 
TwrpBuilder shows that i haven't root but i have it
![screenshot_ - - - - -](https://user-images.githubusercontent.com/32192017/44986131-59666d80-af8b-11e8-83eb-df51a7ff4775.png)
![screenshot_ - - - - -](https://user-images.githubusercontent.com/32192017/44986132-59666d80-af8b-11e8-84c0-2d1d2217102b.png)

**Comment by berkantkz** [comment]
Have you tried to backup recovery and it failed?

**Comment by mohammadshaba** [comment]
It don't fail

**Comment by mohammadshaba** [comment]
But it is run without root

**Comment by mohammadshaba** [comment]
![screenshot_ - - - - -](https://user-images.githubusercontent.com/32192017/44987102-a730a500-af8e-11e8-91ce-c5ddecfa96e5.png)

**Comment by amitkhairnar44** [comment]
Can you send screenshot of TwrpBuilder directory from your device storage?

**Comment by mohammadshaba** [comment]
No TwrpBuilder dir

**Comment by surendrajat** [comment]
What device is it?

**Comment by mohammadshaba** [comment]
Sm-J200H

**Comment by surendrajat** [comment]
Man, we already have built twrp for this device. Why would you request again?

**Comment by berkantkz** [comment]
So closed @Surendrajat?

**Comment by mohammadshaba** [comment]
I know that but this is an issue

**Comment by berkantkz** [comment]
Yes. We didn't say that it's not an issue either. We'll look onto it but as I labeled, it's not that important.

**Comment by surendrajat** [comment]
@mohammadshaba we understand that but as long as it's working somehow, it's good.
