### ISSUE TITLE
join twrpbuilder team

### ISSUE THREAD

**Issue by mohammadshaba** [Grace5921/TwrpBuilder#25]
hello 
how can i join twrpbuilder team

**Comment by Dyneteve** [comment]
Nonono you made multiple accounts over in the tg group you got banned on them all and now you want to join twrpbuilder? Closed

**Comment by mohammadshaba** [comment]
This not a reason

**Comment by mohammadshaba** [comment]
Then i have compiled twrp recoveries and it works

**Comment by mohammadshaba** [comment]
In the group i don't spam i ask only questions about compiling

**Comment by surendrajat** [comment]
@mohammadshaba 
Did we not point you to the compiling wiki?
Did I not help you in PM about your compiling errors?
Did we not provide you the working tree for you to do experiments?
You still kept asking about fixing your tree, why?
And then you go saying like "If you ban me now, I will create another account", why??
Was that a "TwrpBuilder support group" or "Twrp Building support group"?
You built recoveries and those works, great!!! However we don't want very knowledgeable people but those who respect others.

**Comment by mohammadshaba** [comment]
i respect all of you

**Comment by mohammadshaba** [comment]
Did I not help you in PM about your compiling errors?
you donnot help me

**Comment by mohammadshaba** [comment]
Did we not provide you the working tree for you to do experiments?
i know but i want to create tree by my self

**Comment by mohammadshaba** [comment]
You still kept asking about fixing your tree, why?
yup but no one help me

**Comment by mohammadshaba** [comment]
And then you go saying like "If you ban me now, I will create another account", why??
i donnot spam then

**Comment by mohammadshaba** [comment]
Was that a "TwrpBuilder support group" or "Twrp Building support group"?
TwrpBuilder support group

**Comment by surendrajat** [comment]
Wonderful! So expected.
Let me tell you a little secret. The way you're commenting here is called "flooding" and it applies in most of such platforms.
Funny thing is, you are not even realising what wrong are you doing. I may sound rude but please work on your attitude if possible and stop commenting here.
You are not making it to the group at any cost now but you can help people in other ways if you really want to.

**Comment by mohammadshaba** [comment]
How can i help them
I don't flood

**Comment by Dyneteve** [comment]
@mohammadshaba "Was that a "TwrpBuilder support group" or "Twrp Building support group"?" yeah TwrpBuilder support grp aka problems with app or shit not "how" to build your "own" twrp by "yourself" and spam "you" get "build" errors or "bugs"

**Comment by Dyneteve** [comment]
So @mohammadshaba

**Comment by Dyneteve** [comment]
Live please and say

**Comment by androidlover5842** [comment]
lol online war .
