### ISSUE TITLE
Failed to create backup.

### ISSUE THREAD

**Issue by imaandrew** [Grace5921/TwrpBuilder#30]
When I try to create a recovery backup with TWRP Builder, I get the error: Failed to create backup. I have an ASUS Zenfone 4 Max (X00HD)

![screenshot_20181007-202007](https://user-images.githubusercontent.com/14946103/46588730-b82d7400-ca6e-11e8-8f5f-a602495c63be.jpg)

**Comment by amitkhairnar44** [comment]
Why are you submitting request when a build is already available?
I see(in screenshot) a build is available for your device.

**Comment by Simonforest97** [comment]
I have the same issue ! 

Brand : Android
Model : AI_ONE
Board: rk30sdk

**Comment by imaandrew** [comment]
It's an older build. Multiple versions have been released since that build.

**Comment by Dyneteve** [comment]
@ThatWeirdAndrew See this https://t.me/twrpbuilder/561 little update also will update the app soon so expect a fix

**Comment by imaandrew** [comment]
Good to know. I'm going to close this issue.
