### ISSUE TITLE
Remove the need for Google Services or prompt user to use MicroG

### ISSUE THREAD

**Issue by CurveOS** [Grace5921/TwrpBuilder#8]
Installed this app just now and at the first run I get prompted to update Google Play Services (which I don't have since I'm running Lineage 14.1 on the phone, but with an older version of TWRP.

Please change that prompt so that people who don't want to readd Google Play store or similar to make it possible to use this app anyway.

**Comment by androidlover5842** [comment]
did you saw this?
https://github.com/microg/android_packages_apps_GmsCore/issues/510
https://github.com/microg/android_packages_apps_GmsCore/issues/507
